# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'piPodNowPlayingScreenmkJZjY.ui'
##
## Created by: Qt User Interface Compiler version 5.15.8
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *  # type: ignore
from PySide2.QtGui import *  # type: ignore
from PySide2.QtWidgets import *  # type: ignore


class Ui_wNowPlaying(object):
    def setupUi(self, wNowPlaying):
        if not wNowPlaying.objectName():
            wNowPlaying.setObjectName(u"wNowPlaying")
        wNowPlaying.setWindowModality(Qt.ApplicationModal)
        wNowPlaying.resize(320, 240)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wNowPlaying.sizePolicy().hasHeightForWidth())
        wNowPlaying.setSizePolicy(sizePolicy)
        wNowPlaying.setMinimumSize(QSize(320, 240))
        wNowPlaying.setMaximumSize(QSize(320, 240))
        wNowPlaying.setSizeIncrement(QSize(320, 240))
        wNowPlaying.setBaseSize(QSize(320, 240))
        wNowPlaying.setFocusPolicy(Qt.StrongFocus)
        icon = QIcon()
        iconThemeName = u"applications-multimedia"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)
        
        wNowPlaying.setWindowIcon(icon)
        self.centralwidget = QWidget(wNowPlaying)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.pgbMediaCurrentPosition = QProgressBar(self.centralwidget)
        self.pgbMediaCurrentPosition.setObjectName(u"pgbMediaCurrentPosition")
        self.pgbMediaCurrentPosition.setGeometry(QRect(48, 180, 220, 15))
        sizePolicy.setHeightForWidth(self.pgbMediaCurrentPosition.sizePolicy().hasHeightForWidth())
        self.pgbMediaCurrentPosition.setSizePolicy(sizePolicy)
        self.pgbMediaCurrentPosition.setValue(26)
        self.pgbMediaCurrentPosition.setTextVisible(False)
        self.pgbMediaCurrentPosition.setOrientation(Qt.Horizontal)
        self.pgbMediaCurrentPosition.setInvertedAppearance(False)
        self.lblCurrentPosition = QLabel(self.centralwidget)
        self.lblCurrentPosition.setObjectName(u"lblCurrentPosition")
        self.lblCurrentPosition.setGeometry(QRect(10, 178, 35, 18))
        font = QFont()
        font.setPointSize(7)
        self.lblCurrentPosition.setFont(font)
        self.lblCurrentTime_2 = QLabel(self.centralwidget)
        self.lblCurrentTime_2.setObjectName(u"lblCurrentTime_2")
        self.lblCurrentTime_2.setGeometry(QRect(275, 178, 35, 18))
        sizePolicy.setHeightForWidth(self.lblCurrentTime_2.sizePolicy().hasHeightForWidth())
        self.lblCurrentTime_2.setSizePolicy(sizePolicy)
        self.lblCurrentTime_2.setFont(font)
        self.lblAlbumArt = QLabel(self.centralwidget)
        self.lblAlbumArt.setObjectName(u"lblAlbumArt")
        self.lblAlbumArt.setGeometry(QRect(10, 0, 150, 150))
        self.lblAlbumArt.setPixmap(QPixmap(u"resources/Moondawn.png"))
        self.lblAlbumArt.setScaledContents(True)
        self.lblSong = QLabel(self.centralwidget)
        self.lblSong.setObjectName(u"lblSong")
        self.lblSong.setGeometry(QRect(177, 5, 120, 21))
        font1 = QFont()
        font1.setFamily(u"Century Gothic")
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)
        self.lblSong.setFont(font1)
        self.lblArtist = QLabel(self.centralwidget)
        self.lblArtist.setObjectName(u"lblArtist")
        self.lblArtist.setGeometry(QRect(177, 25, 120, 21))
        self.lblArtist.setFont(font1)
        self.lblAlbum = QLabel(self.centralwidget)
        self.lblAlbum.setObjectName(u"lblAlbum")
        self.lblAlbum.setGeometry(QRect(177, 45, 120, 21))
        self.lblAlbum.setFont(font1)
        self.lblPlaylist = QLabel(self.centralwidget)
        self.lblPlaylist.setObjectName(u"lblPlaylist")
        self.lblPlaylist.setGeometry(QRect(177, 85, 120, 21))
        font2 = QFont()
        font2.setFamily(u"Century Gothic")
        font2.setPointSize(9)
        font2.setBold(False)
        font2.setWeight(50)
        self.lblPlaylist.setFont(font2)
        self.lblGenre = QLabel(self.centralwidget)
        self.lblGenre.setObjectName(u"lblGenre")
        self.lblGenre.setGeometry(QRect(177, 65, 120, 21))
        self.lblGenre.setFont(font2)
        self.lblRepeat = QLabel(self.centralwidget)
        self.lblRepeat.setObjectName(u"lblRepeat")
        self.lblRepeat.setGeometry(QRect(139, 154, 18, 18))
        self.lblRepeat.setPixmap(QPixmap(u"resources/repeat.svg"))
        self.lblRepeat.setScaledContents(True)
        self.lblShuffle = QLabel(self.centralwidget)
        self.lblShuffle.setObjectName(u"lblShuffle")
        self.lblShuffle.setGeometry(QRect(13, 154, 18, 18))
        self.lblShuffle.setPixmap(QPixmap(u"resources/shuffle.svg"))
        self.lblShuffle.setScaledContents(True)
        self.pgbVolume = QProgressBar(self.centralwidget)
        self.pgbVolume.setObjectName(u"pgbVolume")
        self.pgbVolume.setGeometry(QRect(298, 0, 15, 140))
        sizePolicy.setHeightForWidth(self.pgbVolume.sizePolicy().hasHeightForWidth())
        self.pgbVolume.setSizePolicy(sizePolicy)
        self.pgbVolume.setAutoFillBackground(False)
        self.pgbVolume.setValue(50)
        self.pgbVolume.setOrientation(Qt.Vertical)
        self.pgbVolume.setTextDirection(QProgressBar.BottomToTop)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(297, 143, 20, 16))
        font3 = QFont()
        font3.setFamily(u"Century Gothic")
        font3.setPointSize(8)
        self.label.setFont(font3)
        self.label.setPixmap(QPixmap(u"resources/medium_volume.svg"))
        self.label.setScaledContents(True)
        self.pbPlayPause = QPushButton(self.centralwidget)
        self.pbPlayPause.setObjectName(u"pbPlayPause")
        self.pbPlayPause.setGeometry(QRect(210, 120, 35, 35))
        self.pbPlayPause.setAutoFillBackground(False)
        self.pbPlayPause.setText(u"")
        icon1 = QIcon()
        icon1.addFile(u"resources/play.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbPlayPause.setIcon(icon1)
        self.pbPlayPause.setIconSize(QSize(75, 75))
        self.pbFastForward = QPushButton(self.centralwidget)
        self.pbFastForward.setObjectName(u"pbFastForward")
        self.pbFastForward.setGeometry(QRect(250, 120, 35, 35))
        self.pbFastForward.setAutoFillBackground(False)
        self.pbFastForward.setText(u"")
        icon2 = QIcon()
        icon2.addFile(u"../resources/fast_forward.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbFastForward.setIcon(icon2)
        self.pbFastForward.setIconSize(QSize(75, 75))
        self.pbRewind = QPushButton(self.centralwidget)
        self.pbRewind.setObjectName(u"pbRewind")
        self.pbRewind.setGeometry(QRect(170, 120, 35, 35))
        self.pbRewind.setAutoFillBackground(False)
        self.pbRewind.setText(u"")
        icon3 = QIcon()
        icon3.addFile(u"../resources/rewind.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pbRewind.setIcon(icon3)
        self.pbRewind.setIconSize(QSize(75, 75))
        wNowPlaying.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(wNowPlaying)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QRect(0, 0, 320, 28))
        self.menubar.setNativeMenuBar(False)
        wNowPlaying.setMenuBar(self.menubar)

        self.retranslateUi(wNowPlaying)

        QMetaObject.connectSlotsByName(wNowPlaying)
    # setupUi

    def retranslateUi(self, wNowPlaying):
        wNowPlaying.setWindowTitle(QCoreApplication.translate("wNowPlaying", u"Now Playing", None))
        self.pgbMediaCurrentPosition.setFormat(QCoreApplication.translate("wNowPlaying", u"%v", None))
        self.lblCurrentPosition.setText(QCoreApplication.translate("wNowPlaying", u"00:00:00", None))
        self.lblCurrentTime_2.setText(QCoreApplication.translate("wNowPlaying", u"00:00:00", None))
        self.lblAlbumArt.setText("")
        self.lblSong.setText(QCoreApplication.translate("wNowPlaying", u"Floating", None))
        self.lblArtist.setText(QCoreApplication.translate("wNowPlaying", u"Klaus Schulze", None))
        self.lblAlbum.setText(QCoreApplication.translate("wNowPlaying", u"Moondawn", None))
        self.lblPlaylist.setText(QCoreApplication.translate("wNowPlaying", u"My Playlist", None))
        self.lblGenre.setText(QCoreApplication.translate("wNowPlaying", u"Kraut Rock", None))
        self.lblRepeat.setText("")
        self.lblShuffle.setText("")
        self.pgbVolume.setFormat(QCoreApplication.translate("wNowPlaying", u"%v", None))
        self.label.setText("")
    # retranslateUi

